import http.client

conn = http.client.HTTPSConnection("api.enphaseenergy.com")
payload = ''
headers = {
  'Authorization': 'Basic M2I1NGVlMTFhMzAzN2FkNDMyYWY4OGIzY2RhMmQ5ZGM6ODhmNTk2NWZmNGM3MzYxYzFlYjg3OTkzODZiMzY0MzM='
}
conn.request("POST", "/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiJ9.eyJhcHBfdHlwZSI6InN5c3RlbSIsInVzZXJfbmFtZSI6ImNhbXB1c2Zhcm1AdW1pY2guZWR1IiwiZW5sX2NpZCI6IiIsImVubF9wYXNzd29yZF9sYXN0X2NoYW5nZWQiOiIxNzI3MTkxNjkyIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImNsaWVudF9pZCI6IjNiNTRlZTExYTMwMzdhZDQzMmFmODhiM2NkYTJkOWRjIiwiYXVkIjpbIm9hdXRoMi1yZXNvdXJjZSJdLCJpc19pbnRlcm5hbF9hcHAiOmZhbHNlLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiYXRpIjoiNGZiZjY0NjYtZDJjNS00M2NlLWI0N2ItY2NjZGNjMTgxN2YxIiwiZXhwIjoxNzMyMTk5Mzg4LCJlbmxfdWlkIjoiNDgxNTIxMSIsImFwcF9JZCI6IjE0MDk2MjQ5ODk1OTUiLCJqdGkiOiJiOGIyNjdkNC1mNDljLTRmMmItYjJkNC0zYTE0YTk1ZWY3NTYifQ.QwNJZVY8Io76eBZF5NRpo0KmvkqjkTEMYMfcRKKin_JyHvrOXa05m3BBiMHqn1LYGwyqgCEVhMrT-mXfEjnn0kCVPjjEL7FXR4degVSqb7Gn3EBHpFoa3W-EZPJqOK3vA-6C5Xqj6X6w6w0x4wdAZ7ONVC2wrK0JhShWshVZzGI", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))