import http.client

conn = http.client.HTTPSConnection("api.enphaseenergy.com")
payload = ''
headers = {
  'Authorization': 'Basic M2I1NGVlMTFhMzAzN2FkNDMyYWY4OGIzY2RhMmQ5ZGM6ODhmNTk2NWZmNGM3MzYxYzFlYjg3OTkzODZiMzY0MzM='
}
conn.request("POST", "/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiJ9.eyJhcHBfdHlwZSI6InN5c3RlbSIsInVzZXJfbmFtZSI6ImNhbXB1c2Zhcm1AdW1pY2guZWR1IiwiZW5sX2NpZCI6IiIsImVubF9wYXNzd29yZF9sYXN0X2NoYW5nZWQiOiIxNzI3MTkxNjkyIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImNsaWVudF9pZCI6IjNiNTRlZTExYTMwMzdhZDQzMmFmODhiM2NkYTJkOWRjIiwiYXVkIjpbIm9hdXRoMi1yZXNvdXJjZSJdLCJpc19pbnRlcm5hbF9hcHAiOmZhbHNlLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiYXRpIjoiNTE0NTJhMWEtMmVmNC00NWQ3LTkwZWQtNTJmMjI4MmQ5MjUwIiwiZXhwIjoxNzMwNjEyMDU5LCJlbmxfdWlkIjoiNDgxNTIxMSIsImFwcF9JZCI6IjE0MDk2MjQ5ODk1OTUiLCJqdGkiOiIwYjdlMmI2Yi1jYTM0LTQ4M2YtOTRkOC1jYzU3MmFjNGViZWYifQ.bHUwFtobhF2wsy3PXnF-hVE1En8x4Kxkmdbqj2EaYA2012E5xsgcw_yrjHInvjsmb0SMeZ3qOgIOu4XnOqvjdubdvvEdSd9q0deDr406VRLIhzdu83Ztfz8JgsiLupwRx1r9G5iIIS37POLC5GflnnRIwod3ldRJXoQ0Gul3Dac", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))